spring:
  kafka:
    bootstrap-servers: localhost:9092   # Kafka broker exposed from Inventory service
    consumer:
      group-id: payment-service-group   # Kafka consumer group
      auto-offset-reset: earliest       # read from beginning if no offset exists
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

payment:
  kafka:
    topic: mtbp-shared-topic
    group: payment-service-group

server:
  port: 8084