name: Java Maven CI

# Trigger on push or PR to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Spring Boot App
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 21 (or the version your project uses)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build the project
      - name: Build with Maven
        run: mvn clean package -B

      # 5️⃣ Optionally, run tests
      - name: Run Tests
        run: mvn test -B
