name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run OWASP Dependency Check (Quick Mode)
        if: github.event_name == 'pull_request'
        run: mvn org.owasp:dependency-check-maven:check -DskipProvidedScope=true -DskipTestScope=true

      - name: Run OWASP Dependency Check (Full Scan)
        if: github.ref == 'refs/heads/main'
        run: mvn org.owasp:dependency-check-maven:check
